export const memories = [
  { id: 1, file: "01.jpg", badge: "Chapter 1", date: "June 7, 2025", location: "MTS Jollibee", title: "The Day We Met 🍟", msg: "Every great love story starts somewhere. Ours started here — and I wouldn't change a thing.", accent: false },
  { id: 2, file: "02.jpg", badge: "Chapter 2", date: "June 22, 2025", location: "Jacks Ridge", title: "Almost a Month 🌸", msg: "Kissed you on the cheek when you weren't expecting it. That smile — I still think about it.", accent: false },
  { id: 3, file: "03.jpg", badge: "The One ♥", date: "June 27, 2025", location: "Catalunan Piqueno", title: "The Day You Said Yes!! 🎉", msg: "Officially together. The happiest moment. Nothing else needs to be said.", accent: true },
  { id: 4, file: "04.jpg", badge: "Chapter 4", date: "July 26, 2025", location: "Ecoland Terminal", title: "Before Our 1st Monthsary 🛫", msg: "Distance tried to get between us. It didn't stand a chance.", accent: false },
  { id: 5, file: "05.jpg", badge: "Chapter 5", date: "August 27, 2025", location: "UM Matina", title: "2nd Monthsary Walk 💐", msg: "A DIY bouquet and a little walk — simple, but that's what makes it perfect.", accent: false },
  { id: 6, file: "06.jpg", badge: "Chapter 6", date: "September 21, 2025", location: "Closest photo", title: "Almost 3 Months 🍂", msg: "No photo from the actual 3rd monthsary — we were a little too busy. You know what I mean. 🙈", accent: false },
  { id: 7, file: "07.jpg", badge: "Chapter 7", date: "October 27, 2025", location: "Christianity", title: "4th Monthsary Date 🧡", msg: "Another month, another reason to be grateful for you.", accent: false },
  { id: 8, file: "08.jpg", badge: "Chapter 8", date: "November 23, 2025", location: "Shrine Hills / Convenience Store", title: "Almost 5 Months ☔", msg: "It rained and you chased me. Colet was there too. A chaotic, beautiful day.", accent: false },
  { id: 9, file: "09.jpg", badge: "Chapter 9", date: "December 20, 2025", location: "Chowking Centerpoint", title: "Almost Half a Year — Matching Shoes! 👟", msg: "LDR again, but we made it. And we got our first matchy running shoes. Twins.", accent: false },
  { id: 10, file: "10.jpg", badge: "Chapter 10", date: "January 27, 2026", location: "SM Lanang / Ribshack", title: "7th Monthsary — Unli Ribs 🍖", msg: "Unli ribs. I miss it already. Can we go again?", accent: false },
  { id: 11, file: "11.jpg", badge: "Chapter 11", date: "February 14, 2026", location: "Coastal Road Bago", title: "Our 1st Valentine's Day 🌹", msg: "Not the fanciest date, but it was ours. Bawi rako puhon, myjagi. I love you so much.", accent: false },
  { id: 12, file: "12.jpg", badge: "Chapter 12", date: "February 26, 2026", location: "Yamashita Diner", title: "Japanese Date Night 🍱", msg: "Japanese food, good vibes, and you.", accent: false },
  { id: 13, file: "13.jpg", badge: "Chapter 13", date: "March 27, 2026", location: "Sukidesu", title: "9th Monthsary — Japanese Again 🍣", msg: "We really like Japanese food, huh. No complaints from me.", accent: false },
  { id: 14, file: "14.jpg", badge: "Chapter 14", date: "April 27, 2026", location: "Your place", title: "10th Monthsary Mini Date 🏠", msg: "Mini date. Kaon and... ehem. 😌 Simple but I loved it.", accent: false },
  { id: 15, file: "15.jpg", badge: "Chapter 15", date: "May 26, 2026", location: "USeP", title: "A Day Before 11 Months ☕", msg: "Chika and mami. One of those quiet days I want to remember forever.", accent: false },
  { id: 16, file: "16.jpg", badge: "1 Year 🥂", date: "June 26, 2026", location: "Our anniversary", title: "And Today Is... 🤎", msg: "Never expected to feel this grateful. Sorry for my mistakes. For more years together — for us. I love you, from Jagi.", accent: true }
];
