export const memories = [
  { id: 1, file: "01.jpg", badge: "Chapter 1", date: "June 7, 2025", location: "MTS Jollibee", title: "1st Meet 🍟", msg: "Payat paku dire jagiiii T_T. Anyway yieee 1st meet nato jok2 pa sha o di daw monkeypox ngiiiiiii", accent: false },
  { id: 2, file: "02.jpg", badge: "Chapter 2", date: "June 22, 2025", location: "Jacks Ridge", title: "Almost a Month Together 🌸", msg: "WAHHSASHAHSASH gi keys tika sa cheeks ani bliiii", accent: false },
  { id: 3, file: "03.jpg", badge: "The One ♥", date: "June 27, 2025", location: "Catalunan Piqueno", title: "The Day You Said Yes!! 🎉", msg: "Gizagot mokooo T_T, Thankkk you sooo matsss", accent: true },
  { id: 4, file: "04.jpg", badge: "Chapter 4", date: "July 26, 2025", location: "Ecoland Terminal", title: "Before Our 1st Monthsary", msg: "LDR TAYUU NETOO T_T WAWA LANG AKUU", accent: false },
  { id: 5, file: "05.jpg", badge: "Chapter 5", date: "August 27, 2025", location: "UM Matina", title: "2nd Monthsary Walk 💐", msg: "Yieeee boom keleg kba boi sa DIY boket kuuu bliiiiii, mas bongga nana puhon mayaman na aku", accent: false },
  { id: 6, file: "06.jpg", badge: "Chapter 6", date: "September 21, 2025", location: "St. Frances Church", title: "Almost 3 Months 🍂", msg: "Wala tayu pic di ko mahanap T_T, basin lingaw kaayo ta wala nata ka pic BWAHAHAAH", accent: false },
  { id: 7, file: "07.jpg", badge: "Chapter 7", date: "October 27, 2025", location: "Christianity", title: "4th Monthsary Date 🧡", msg: "Nag ditdit tau sa Christianity yeyyyy soafer solitttt", accent: false },
  { id: 8, file: "08.jpg", badge: "Chapter 8", date: "November 23, 2025", location: "Shrine Hills / Convenience Store", title: "Almost 5 Months ☔", msg: "Jogging tau neto pa DGT, ka kyot kazama nya pa idol nya yieeee", accent: false },
  { id: 9, file: "09.jpg", badge: "Chapter 9", date: "December 20, 2025", location: "Chowking Centerpoint", title: "Almost Half a Year 👟", msg: "LDR tauuu T_T naa ko bohol, pero yeyyy ty mama naa tay new shoes", accent: false },
  { id: 10, file: "10.jpg", badge: "Chapter 10", date: "January 27, 2026", location: "SM Lanang / Ribshack", title: "7th Monthsary — Ribshack 🍖", msg: "Na discover ko ribshack hhuhu balik tau don soon", accent: false },
  { id: 11, file: "11.jpg", badge: "Chapter 11", date: "February 14, 2026", location: "Coastal Road Bago", title: "Our 1st Valentine's Day 🌹", msg: "Not the fanciest date, but it was our valentine's day together. Bawi rako puhon, myjagi. I love you so much.", accent: false },
  { id: 12, file: "12.jpg", badge: "Chapter 12", date: "February 26, 2026", location: "Yamashita Diner", title: "Japanese Date Night 🍱", msg: "HUHUHUH gi lebre mo pa aku netooo, ARIGATHANKYOU GOZAIMUCH myjagiii", accent: false },
  { id: 13, file: "13.jpg", badge: "Chapter 13", date: "March 27, 2026", location: "Sukidesu", title: "9th Monthsary 🍣", msg: "Nadala mo na talaga aku sa Sukidesu, SAMANI DESU KA??! OHAYOUNG ADLAW!!! PALIHUGAISHIMASU!!!!!", accent: false },
  { id: 14, file: "14.jpg", badge: "Chapter 14", date: "April 27, 2026", location: "Bording Hauz", title: "10th Monthsary Mini Date 🏠", msg: "Mini date. TY sa pa pizza jagibordsz.", accent: false },
  { id: 15, file: "15.jpg", badge: "Chapter 15", date: "May 26, 2026", location: "USeP", title: "A Day Before 11 Months ☕", msg: "Chika and mami za obrero, tenkyu myjagiiii", accent: false },
];
